service: stella-serverless
app: stella-serverless
org: patrickmcgrath29

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dotenv-plugin
  - serverless-domain-manager

custom:
  wsgi:
    app: src.app
    packRequirements: false
  customDomain:
    domainName: urls.patrickmcgrath.io
    basePath: ''
    stage: prod
    createRoute53Record: true

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: us-east-1

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
        cors: true
      - http: 'ANY {proxy+}'
        cors: true
